apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: wackorder-bot
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: wackorder-bot
  path: ./deploy/overlays/production
  prune: true
  targetNamespace: wackorder
  postBuild:
    substitute: {}
