apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: wackorder
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/BarthV/wackorder-bot.git
  ref:
    branch: main
