apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-apps-root
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: infra-cd
  path: ./deploy/overlays
  prune: false
  postBuild:
    substitute: {}
