apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: root-cd
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: wackorder-bot
  path: ./deploy/infra
  prune: false
  targetNamespace: wackorder-dev
  postBuild:
    substitute: {}
