apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wackorder

labels:
  - pairs:
      app.kubernetes.io/part-of: wackorder-bot
    includeSelectors: false

resources:
  - namespace.yaml
  - deployment.yaml
  - pvc.yaml

configMapGenerator:
  - name: wackorder-bot
    literals:
      - LOG_LEVEL=info
    options:
      labels:
        app.kubernetes.io/name: wackorder-bot
