apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: wackorder-bot
  namespace: flux-system
spec:
  interval: 2m
  image: ghcr.io/barthv/wackorder-bot
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: wackorder-bot
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: wackorder-bot
  filterTags:
    pattern: '^v(?P<version>[0-9]+\.[0-9]+\.[0-9]+.*)$'
    extract: '$version'
  policy:
    semver:
      range: 0.x
