apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - image-policy.yaml
  - image-updater.yaml

images:
  - name: wackorder-bot
    newName: ghcr.io/barthv/wackorder-bot

configMapGenerator:
  - name: wackorder-bot
    behavior: merge
    literals:
      - LOG_LEVEL=info
      - LOG_CHANNEL_ID=1483550466942963954
      - ADMIN_ROLE_IDS=1483588423749996564
      - CORP_ID=1482661212977234113
